---
- hosts: k8s_nodes
  become: yes
  become_user: root
  become_method: sudo

### Init K8S Cluster
  tasks:
  - name: Turnoff Swap
    command: swapoff -a

  - name: Modify /etc/docker/daemon.json
    copy:
        src: "files/docker-daemon.json"
        dest: "/etc/docker/daemon.json"
        mode: 0644

  - name: Init Master
    shell: "pgrep flanneld || kubeadm init --pod-network-cidr=10.244.0.0/16"
    when: "node_type == 'master'"

  - name: Setup kube config on Master
    shell: "cp -f /etc/kubernetes/admin.conf /home/{{ansible_ssh_user}}/.kube/config"
    when: "node_type == 'master'"

  - name: Fetch kube config to localhost
    fetch:
        src: /etc/kubernetes/admin.conf
        dest: files/admin.conf
        flat: true
    when: "node_type == 'master'"

  - name: Setup kube config on localhost
    shell: "cp -f files/admin.conf $HOME/.kube/config"
    delegate_to: localhost
    become: no
    run_once: true

  - name: Start networking on localhost
    shell: "kubectl apply -f files/kube-flannel.yml"
    delegate_to: localhost
    become: no
    run_once: true

  - name: Start dashboard on localhost
    shell: "kubectl apply -f files/kubernetes-dashboard.yaml"
    delegate_to: localhost
    become: no
    run_once: true

  - name: Create new master token (valid 1 hour only)
    shell: "kubeadm token create --print-join-command > /tmp/join_master.sh"
    register: master_token
    when: "node_type == 'master'"

  - name: Fetch token to localhost
    fetch:
        src: /tmp/join_master.sh
        dest: files/join_master.sh
        flat: true
    when: "node_type == 'master'"

  - name: Copy token to nodes
    copy:
      src: files/join_master.sh
      dest: /tmp/join_master.sh
    when: "node_type == 'node'"

  - name: Start slaves
    shell: "pgrep flanneld || sh /tmp/join_master.sh"
    when: "node_type == 'node'"

### EoF
